# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c4cdb99c9d674e6541c770ef9e3caaf9a3eddabc7d5dda714366ca7bdc78718f5ca4c6117d92f75919720cb9a3ebbc840261865a28c3f820086227e8c10c09

test:
  secret_key_base: d733cdce90f4fa2be30a67bed3841be22d18d543f9f5b40927f33a482b36e642ec546d4f8d933cfa87757690bd4aebaeb97e8a6371b134ff5a9dd93be30a50ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
